OK

diff --git a/install_pack_loops b/install_pack_loops
--- a/install_pack_loops
+++ b/install_pack_loops
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 ID=$(id -u)
 TIMESTAMP=$(date +%F-%H-%M-%S)
 LOGFILE="/tmp/$0-$TIMESTAMP.log"
@@ -10,7 +12,7 @@ N="\e[0m"
 validate(){
      if [ $1 -ne 0 ]
 then
-    echo -e " $2  is $R failed $N"
+    echo -e " ERROR:  is $R failed $N"
     exit 1
 else
     echo -e "$2 is $G success $N"
@@ -25,11 +27,12 @@ else
     echo -e "$G you are root user $N"
 fi
 
-yum install mysql -y &>> $LOGFILE
-
-validate $? "installing mysql"
-
-yum install git -y &>> $LOGFILE
-
-validate $? "installing git"
-
+for package in $@
+do
+    yum list installed $package
+    if[ $? -ne 0 ]
+    then
+        yum install $package -y
+        validate $? "$package installation"
+    else
+        echo -e "$package is already in"
